# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce.Api/Dockerfile
    ports:
      - 8080:8080
